class CategoryManager {
  // Singleton-Pattern für einfachen Zugriff
  static final CategoryManager _instance = CategoryManager._internal();
  factory CategoryManager() => _instance;
  CategoryManager._internal();

  // Kategorien mit ihren Wörtern und Imposter-Hinweisen
  final Map<String, Map<String, String>> categoryWords = {
    'Unterhaltung': {
      'Film': 'Oscar',
      'Serie': 'Staffel',
      'Netflix': 'Binge',
      'Kino': 'Popcorn',
      'Theater': 'Vorhang',
      'Konzert': 'Moshpit',
      'Musik': 'Rhythmus',
      'Buch': 'Seite',
      'Zeitung': 'Schlagzeile',
      'Magazin': 'Bilder',
      'Radio': 'DJ',
      'Podcast': 'Spotify',
      'YouTube': 'Creator',
      'Streaming': 'Twitch',
      'Gaming': 'Level',
      'Comic': 'Speechbubble',
      'Manga': 'japan',
      'Anime': 'japan',
      'Theaterstück': 'Akt',
      'Oper': 'Klassik',
      'Ballett': 'Schwahnensee',
      'Musical': 'Ensemble',
      'Festival': 'Camping',
      'Party': 'Playlist',
      'Disco': 'Kugel',
      'Karaoke': 'Mikrofon',
      'Tanz': 'Choreo',
      'Museum': 'Exponat',
      'Zirkus': 'Manege',
      'Stand-up': 'Punchline',
      'Comedy': 'Gag',
      'Reality-TV': 'Drama',
      'Quiz': 'Joker',
      'Talk-Show': 'Gast',
      'Sportübertragung': 'Replay'
    },
    'Alltag': {
      'Kochen': 'Rezept',
      'Backen': 'Teig',
      'Einkaufen': 'Korb',
      'Waschen': 'Waschmittel',
      'Bügeln': 'Dampf',
      'Putzen': 'Lappen',
      'Schlafen': 'Traum',
      'Arbeiten': 'Deadline',
      'Studieren': 'Semester',
      'Lernen': 'Karteikarte',
      'Lesen': 'Buchstabe',
      'Schreiben': 'Tinte',
      'Telefonieren': 'Anrufbeantworter',
      'E-Mail': 'Spam',
      'Internet': 'Browser',
      'Soziale Medien': 'Feed',
      'Sport': 'Schweiß',
      'Spazieren': 'Schritt',
      'Radfahren': 'Kette',
      'Auto fahren': 'Blinker',
      'Bus fahren': 'Haltestelle',
      'Zug fahren': 'Gleis',
      'Fliegen': 'Turbulenz',
      'Reisen': 'Koffer',
      'Urlaub': 'Souvenir',
      'Feiern': 'Gastgeber',
      'Geburtstag': 'Kerze',
      'Hochzeit': 'Ring',
      'Familie': 'Essen',
      'Freunde': 'Treffen',
      'Haustiere': 'Futter',
      'Garten': 'Samen',
      'Haushalt': 'Putzen',
      'Reparatur': 'Werkzeug',
      'Basteln': 'Kleber'
    },
    'Natur': {
      'Wald': 'Blätter',
      'Berg': 'Schnee',
      'See': 'Strand',
      'Fluss': 'Strömung',
      'Meer': 'Ebbe',
      'Strand': 'Sand',
      'Wüste': 'Oase',
      'Regenwald': 'Lianen',
      'Gletscher': 'Spalten',
      'Vulkan': 'Magma',
      'Höhle': 'Quelle',
      'Wasserfall': 'Nebel',
      'Canyon': 'Groß',
      'Insel': 'Palme', 
      'Küste': 'Sonne',
      'Tal': 'Schlucht',
      'Hügel': 'Hoch',
      'Wiese': 'Blume',
      'Blume': 'Nektar',
      'Baum': 'Blatt',
      'Pflanze': 'Photosynthese',
      'Tier': 'Lebensraum',
      'Vogel': 'Feder',
      'Fisch': 'Schuppen',
      'Insekt': 'Fühler',
      'Säugetier': 'Fell',
      'Reptil': 'Schuppe',
      'Gras': 'Halme',
      'Strauch': 'Beere',
      'Kaktus': 'Wüste',
      'Alge': 'Plankton'
    },
    'Technik': {
      'Computer': 'Prozessor',
      'Smartphone': 'App',
      'Tablet': 'Touch',
      'Laptop': 'Akku',
      'Server': 'Cloud',
      'Router': 'WLAN',
      'Internet': 'IP',
      'WLAN': 'Funk',
      'Bluetooth': 'Pairing',
      'USB': 'Port',
      'Kamera': 'Objektiv',
      'Drucker': 'Toner',
      'Scanner': 'Auflösung',
      'Monitor': 'Pixel',
      'Tastatur': 'Layout',
      'Maus': 'DPI',
      'Lautsprecher': 'Watt',
      'Mikrofon': 'Membran',
      'Webcam': 'Stream',
      'Festplatte': 'Partition',
      'Prozessor': 'Cache',
      'Grafikkarte': 'Shader',
      'RAM': 'Speicher',
      'Netzwerk': 'Protokoll',
      'Software': 'Code',
      'App': 'Update',
      'Betriebssystem': 'Kernel',
      'Programmierung': 'Syntax',
      'Datenbank': 'Query',
      'Cloud': 'Sync',
      'Backup': 'Restore',
      'Virus': 'Quarantäne',
      'Firewall': 'Port',
      'Passwort': 'Hash',
      'Verschlüsselung': 'Key',
      'Update': 'Patch',
      'Bug': 'Debug',
      'Feature': 'Release',
      'Interface': 'UI',
      'Algorithmus': 'Komplexität'
    },
    'Sport': {
      'Fußball': 'Elfmeter',
      'Basketball': 'Amerika',
      'Tennis': 'Aufschlag',
      'Volleyball': 'Block',
      'Handball': 'Wurfkreis',
      'Hockey': 'Bully',
      'Golf': 'Green',
      'Baseball': 'Home Run',
      'Cricket': 'Wicket',
      'Rugby': 'Scrum',
      'Boxen': 'K.o.',
      'Kampfsport': 'Gürtel',
      'Judo': 'Wurf',
      'Fechten': 'Anzug',
      'Schwimmen': 'Kraulen',
      'Tauchen': 'Druck',
      'Surfen': 'Welle',
      'Segeln': 'Meer',
      'Rudern': 'Schlauch',
      'Kanu': 'Paddel',
      'Skifahren': 'Schnee',
      'Snowboard': 'Halfpipe',
      'Eislaufen': 'Pirouette',
      'Curling': 'Stein',
      'Formel 1': 'Pitstop',
      'Radfahren': 'Frankreich',
      'Laufen': 'Sprint',
      'Marathon': 'Mauer',
      'Triathlon': 'Wechsel',
      'Turnen': 'Salto',
      'Gymnastik': 'Übung'
    },
    'Wissenschaft': {
      'Physik': 'Quanten',
      'Chemie': 'Reaktion',
      'Biologie': 'Zelle',
      'Astronomie': 'Galaxie',
      'Geologie': 'Tektonik',
      'Meteorologie': 'Front',
      'Ökologie': 'System',
      'Botanik': 'Photosynthese',
      'Anatomie': 'Organ',
      'Medizin': 'Diagnose',
      'Psychologie': 'Verhalten',
      'Soziologie': 'Gesellschaft',
      'Pädagogik': 'Lernprozess',
      'Philosophie': 'These',
      'Geschichte': 'Epoche',
      'Archäologie': 'Ausgrabung',
      'Linguistik': 'Syntax',
      'Mathematik': 'Formel',
      'Statistik': 'Stichprobe',
      'Informatik': 'Algorithmus',
      'Robotik': 'Sensor',
      'Künstliche Intelligenz': 'Google',
      'Genetik': 'DNA',
      'Evolution': 'Mutation',
      'Relativität': 'Raumzeit',
      'Kardiologie': 'Herz',
      'Neurologie': 'Nerv'
    },
    'Geschichte': {
      'Antike': 'Orakel',
      'Mittelalter': 'Burg',
      'Renaissance': 'Humanismus',
      'Aufklärung': 'Vernunft',
      'Industrialisierung': 'Dampfmaschine',
      'Moderne': 'Globalisierung',
      'Zeitgeschichte': 'Digitalisierung',
      'Prähistorie': 'Höhlenmalerei',
      'Altertum': 'Pyramide',
      'Frühgeschichte': 'Schrift',
      'Mittelalter': 'Ritter',
      'Neuzeit': 'Entdeckung',
      'Gegenwart': 'Technologie',
      'Zukunft': 'Vision',
      'Revolution': 'Umsturz',
      'Krieg': 'Schlacht',
      'Frieden': 'Vertrag',
      'Demokratie': 'Wahl',
      'Monarchie': 'Thron',
      'Diktatur': 'Regime',
      'Republik': 'Verfassung',
      'Kaiserreich': 'Krone',
      'Königreich': 'Hof',
      'Fürstentum': 'Residenz',
      'Stadtstaat': 'Mauer',
      'Bundesstaat': 'Föderation',
      'Staatenbund': 'Allianz',
      'Weltreich': 'Kolonie',
      'Kolonialreich': 'Siedlung',
      'Imperium': 'Provinz',
      'Dynastie': 'Erbfolge',
      'Herrschaft': 'Macht',
      'Regierung': 'Kabinett',
      'Parlament': 'Abgeordneter',
      'Verfassung': 'Grundgesetz',
      'Gesetz': 'Paragraph',
      'Recht': 'Urteil',
      'Justiz': 'Gericht',
      'Polizei': 'Wache'
    },
    'Geographie': {
      'Kontinent': 'Plattentektonik',
      'Ozean': 'Tiefsee',
      'Meer': 'Gezeiten',
      'See': 'Ufer',
      'Fluss': 'Mündung',
      'Berg': 'Gipfel',
      'Tal': 'Schlucht',
      'Hügel': 'Hang',
      'Ebene': 'Horizont',
      'Wüste': 'Oase',
      'Regenwald': 'Canopy',
      'Savanne': 'Akazie',
      'Steppe': 'Grasland',
      'Tundra': 'Permafrost',
      'Gletscher': 'Moräne',
      'Vulkan': 'Krater',
      'Insel': 'Archipel',
      'Halbinsel': 'Isthmus',
      'Archipel': 'Atoll',
      'Küste': 'Brandung',
      'Strand': 'Düne',
      'Klippe': 'Fels',
      'Canyon': 'Schlucht',
      'Höhle': 'Stalaktit',
      'Grotte': 'Tropfstein',
      'Fjord': 'Gletscher',
      'Delta': 'Sediment',
      'Mündung': 'Ästuar',
      'Quelle': 'Ursprung',
      'Wasserfall': 'Kaskade',
      'Geysir': 'Eruption',
      'Oase': 'Palme',
      'Atoll': 'Lagune',
      'Riff': 'Koralle',
      'Lagune': 'Sandbank',
      'Bucht': 'Hafen',
      'Golf': 'Meerenge',
      'Straße': 'Narrow',
      'Kanal': 'Schleuse'
    },
    'Kunst': {
      'Malerei': 'Pinsel',
      'Zeichnung': 'Skizze',
      'Skulptur': 'Modell',
      'Architektur': 'Entwurf',
      'Fotografie': 'Blende',
      'Film': 'Storyboard',
      'Musik': 'Komposition',
      'Tanz': 'Choreografie',
      'Theater': 'Inszenierung',
      'Literatur': 'Manuskript',
      'Poesie': 'Metapher',
      'Design': 'Konzept',
      'Mode': 'Collection',
      'Grafik': 'Layout',
      'Illustration': 'Sketch',
      'Karikatur': 'Übertreibung',
      'Comic': 'Panel',
      'Manga': 'Chapter',
      'Anime': 'Animation',
      'Kalligrafie': 'Schriftzug',
      'Gravur': 'Stich',
      'Druck': 'Auflage',
      'Lithografie': 'Stein',
      'Radierung': 'Ätzung',
      'Holzschnitt': 'Schnitt',
      'Siebdruck': 'Schablone',
      'Töpferei': 'Drehscheibe',
      'Keramik': 'Brennen',
      'Glas': 'Schmelze',
      'Schmuck': 'Fassung',
      'Textil': 'Webstuhl',
      'Tapisserie': 'Wandteppich',
      'Mosaik': 'Tessera',
      'Fresko': 'Putz',
      'Glasmalerei': 'Blei',
      'Buchmalerei': 'Illumination',
      'Miniatur': 'Detail',
      'Porträt': 'Profil',
      'Landschaft': 'Horizont',
      'Stillleben': 'Komposition'
    },
    'Stars & Promis': {
      'Helene Fischer': 'Schlager',
      'Thomas Gottschalk': 'Wetten',
      'Stefan Raab': 'TV',
      'Joko Winterscheidt': 'Duell',
      'Klaas Heufer-Umlauf': 'Duell',
      'Günther Jauch': 'Quiz',
      'Barbara Schöneberger': 'Show',
      'Elyas M\'Barek': 'Film',
      'Matthias Schweighöfer': 'Film',
      'Til Schweiger': 'Film',
      'Jan Böhmermann': 'Satire',
      'Mark Forster': 'Musik',
      'Max Giesinger': 'Musik',
      'Wincent Weiss': 'Musik',
      'Sarah Connor': 'Musik',
      'Markus Lanz': 'Talk',
      'Bastian Pastewka': 'Comedy',
      'Anke Engelke': 'Comedy',
      'Mario Barth': 'Comedy',
      'Felix Lobrecht': 'Comedy',
      'Faisal Kawusi': 'Comedy',
      'Lena Meyer-Landrut': 'ESC',
      'Michael Schumacher': 'Formel 1',
      'Sebastian Vettel': 'Formel 1',
      'Manuel Neuer': 'Fußball',
      'Toni Kroos': 'Fußball',
      'Bastian Schweinsteiger': 'Fußball',
      'Angela Merkel': 'Politik',
      'Olaf Scholz': 'Politik',
      'Robert Habeck': 'Politik',
      'Christian Lindner': 'Politik',
      'Alice Weidel': 'Politik'
    }
  };

  // Gibt ein zufälliges Wort und seinen Hinweis aus den ausgewählten Kategorien zurück
  Map<String, String> getRandomWordWithHint(List<String> selectedCategories) {
    if (selectedCategories.isEmpty) {
      throw Exception('Keine Kategorien ausgewählt');
    }

    // Sammle alle Wörter und Hinweise aus den ausgewählten Kategorien
    List<Map<String, String>> allWordsWithHints = [];
    for (String category in selectedCategories) {
      if (categoryWords.containsKey(category)) {
        categoryWords[category]!.forEach((word, hint) {
          allWordsWithHints.add({'word': word, 'hint': hint});
        });
      }
    }

    if (allWordsWithHints.isEmpty) {
      throw Exception('Keine Wörter in den ausgewählten Kategorien gefunden');
    }

    // Wähle ein zufälliges Wort mit Hinweis aus
    allWordsWithHints.shuffle();
    return {
      'word': allWordsWithHints.first['word']!,
      'hint': allWordsWithHints.first['hint']!
    };
  }

  // Gibt alle Wörter einer bestimmten Kategorie zurück
  List<String> getWordsForCategory(String category) {
    return categoryWords[category]?.keys.toList() ?? [];
  }

  // Gibt alle verfügbaren Kategorien zurück
  List<String> getAvailableCategories() {
    return categoryWords.keys.toList();
  }
} 