class CategoryManager {
  // Singleton-Pattern für einfachen Zugriff
  static final CategoryManager _instance = CategoryManager._internal();
  factory CategoryManager() => _instance;
  CategoryManager._internal();

  // Kategorien mit ihren Wörtern und Imposter-Hinweisen
  final Map<String, Map<String, String>> categoryWords = {
    'Unterhaltung': {
      'Film': 'Hollywood',
      'Serie': 'Streaming',
      'Netflix': 'Plattform',
      'Kino': 'Leinwand',
      'Theater': 'Bühne',
      'Konzert': 'Musik',
      'Musik': 'Melodie',
      'Buch': 'Verlag',
      'Zeitung': 'Nachrichten',
      'Magazin': 'Zeitschrift',
      'Radio': 'Audio',
      'Podcast': 'Audio',
      'YouTube': 'Video',
      'Streaming': 'Online',
      'Gaming': 'Controller',
      'Comic': 'Zecihnung',
      'Manga': 'Japan',
      'Anime': 'Japan',
      'Theaterstück': 'Bühne',
      'Oper': 'Gesang',
      'Ballett': 'Tanz',
      'Musical': 'Singen',
      'Festival': 'Event',
      'Party': 'Musik',
      'Disco': 'Tanz',
      'Karaoke': 'Singen',
      'Tanz': 'Bewegung',
      'Kunstausstellung': 'Mona Lisa',
      'Museum': 'Ausstellung',
      'Galerie': 'Kunst',
      'Zirkus': 'Artisten',
      'Stand-up': 'Humor',
      'Comedy': 'Lachen',
      'Reality-TV': 'Show',
      'Quiz': 'Fragen',
      'Talk-Show': 'Gespräch',
      'Sportübertragung': 'Live'
    },
    'Alltag': {
      'Kochen': 'Küche',
      'Backen': 'Ofen',
      'Einkaufen': 'Laden',
      'Waschen': 'Wasser',
      'Bügeln': 'Kleidung',
      'Putzen': 'Sauber',
      'Aufräumen': 'Ordnung',
      'Schlafen': 'Bett',
      'Arbeiten': 'Job',
      'Studieren': 'Lernen',
      'Lernen': 'Wissen',
      'Lesen': 'Buch',
      'Schreiben': 'Stift',
      'Telefonieren': 'Anruf',
      'E-Mail': 'Nachricht',
      'Internet': 'Online',
      'Soziale Medien': 'Netzwerk',
      'Sport': 'Bewegung',
      'Spazieren': 'Gehen',
      'Radfahren': 'Fahrrad',
      'Auto fahren': 'Fahrzeug',
      'Bus fahren': 'Transport',
      'Zug fahren': 'Bahn',
      'Fliegen': 'Flugzeug',
      'Reisen': 'Urlaub',
      'Urlaub': 'Ferien',
      'Feiern': 'Party',
      'Geburtstag': 'Jahrestag',
      'Hochzeit': 'Brautpaar',
      'Familie': 'Verwandte',
      'Freunde': 'Bekannte',
      'Haustiere': 'Tiere',
      'Garten': 'Pflanzen',
      'Haushalt': 'Haus',
      'Reparatur': 'Reparieren',
      'Basteln': 'Kreativ'
    },
    'Natur': {
      'Wald': 'Bäume',
      'Berg': 'Höhe',
      'See': 'Wasser',
      'Fluss': 'Strom',
      'Meer': 'Ozean',
      'Strand': 'Sand',
      'Wüste': 'Sand',
      'Savanne': 'Grasland',
      'Regenwald': 'Tropen',
      'Gletscher': 'Eis',
      'Vulkan': 'Lava',
      'Höhle': 'Dunkel',
      'Wasserfall': 'Fall',
      'Canyon': 'Schlucht',
      'Insel': 'Wasser',
      'Küste': 'Strand',
      'Tal': 'Senke',
      'Hügel': 'Erhebung',
      'Wiese': 'Gras',
      'Blume': 'Pflanze',
      'Baum': 'Wald',
      'Pflanze': 'Wachstum',
      'Tier': 'Lebewesen',
      'Vogel': 'Fliegen',
      'Fisch': 'Schwimmen',
      'Insekt': 'Krabbeln',
      'Säugetier': 'Warmblüter',
      'Reptil': 'Kaltblüter',
      'Amphibie': 'Wasser',
      'Pilz': 'Sporen',
      'Moos': 'Grün',
      'Farn': 'Blatt',
      'Gras': 'Wiese',
      'Strauch': 'Busch',
      'Kaktus': 'Dornen',
      'Alge': 'Wasser',
      'Koralle': 'Riff',
      'Muschel': 'Schale'
    },
    'Technik': {
      'Computer': 'Elektronik',
      'Smartphone': 'Mobil',
      'Tablet': 'Touchscreen',
      'Laptop': 'Tragbar',
      'Server': 'Netzwerk',
      'Router': 'Internet',
      'Internet': 'Online',
      'WLAN': 'Drahtlos',
      'Bluetooth': 'Verbindung',
      'USB': 'Anschluss',
      'Kamera': 'Foto',
      'Drucker': 'Papier',
      'Scanner': 'Digital',
      'Monitor': 'Bildschirm',
      'Tastatur': 'Eingabe',
      'Maus': 'Zeiger',
      'Lautsprecher': 'Ton',
      'Mikrofon': 'Sprache',
      'Webcam': 'Video',
      'Festplatte': 'Speicher',
      'Prozessor': 'CPU',
      'Grafikkarte': 'GPU',
      'RAM': 'Arbeitsspeicher',
      'Netzwerk': 'Verbindung',
      'Software': 'Programm',
      'App': 'Anwendung',
      'Betriebssystem': 'OS',
      'Programmierung': 'Code',
      'Datenbank': 'Speicher',
      'Cloud': 'Online',
      'Backup': 'Sicherung',
      'Virus': 'Schädlich',
      'Firewall': 'Schutz',
      'Passwort': 'Sicherheit',
      'Verschlüsselung': 'Sicher',
      'Update': 'Aktualisierung',
      'Bug': 'Fehler',
      'Feature': 'Funktion',
      'Interface': 'Oberfläche',
      'Algorithmus': 'Berechnung'
    },
    'Sport': {
      'Fußball': 'Ball',
      'Basketball': 'Korb',
      'Tennis': 'Schläger',
      'Volleyball': 'Netz',
      'Handball': 'Tor',
      'Hockey': 'Schläger',
      'Golf': 'Schläger',
      'Baseball': 'Schläger',
      'Cricket': 'Schläger',
      'Rugby': 'Ei',
      'Boxen': 'Ring',
      'Kampfsport': 'Kampf',
      'Judo': 'Gi',
      'Karate': 'Gi',
      'Taekwondo': 'Gi',
      'Fechten': 'Degen',
      'Schwimmen': 'Wasser',
      'Tauchen': 'Wasser',
      'Surfen': 'Welle',
      'Segeln': 'Boot',
      'Rudern': 'Boot',
      'Kanu': 'Boot',
      'Skifahren': 'Schnee',
      'Snowboard': 'Schnee',
      'Eislaufen': 'Eis',
      'Eishockey': 'Puck',
      'Curling': 'Stein',
      'Bobsport': 'Schlitten',
      'Rennsport': 'Auto',
      'Formel 1': 'Rennen',
      'Rallye': 'Strecke',
      'Radfahren': 'Rad',
      'Laufen': 'Sprint',
      'Marathon': 'Lang',
      'Triathlon': 'Drei',
      'Turnen': 'Boden',
      'Gymnastik': 'Bewegung',
      'Yoga': 'Dehnung',
      'Pilates': 'Körper'
    },
    'Kultur': {
      'Theater': 'Bühne',
      'Oper': 'Gesang',
      'Ballett': 'Tanz',
      'Musical': 'Show',
      'Konzert': 'Musik',
      'Festival': 'Event',
      'Ausstellung': 'Kunst',
      'Museum': 'Sammlung',
      'Galerie': 'Kunst',
      'Kino': 'Film',
      'Literatur': 'Buch',
      'Poesie': 'Gedicht',
      'Drama': 'Theater',
      'Komödie': 'Lachen',
      'Tragödie': 'Trauer',
      'Satire': 'Humor',
      'Karikatur': 'Zeichnung',
      'Comic': 'Bilder',
      'Manga': 'Japan',
      'Anime': 'Animation',
      'Fotografie': 'Foto',
      'Architektur': 'Gebäude',
      'Design': 'Gestaltung',
      'Mode': 'Kleidung',
      'Kulinarik': 'Essen',
      'Wein': 'Traube',
      'Bier': 'Hopfen',
      'Kaffee': 'Bohne',
      'Tee': 'Blatt',
      'Kochkunst': 'Küche',
      'Backkunst': 'Ofen',
      'Handwerk': 'Kunst',
      'Töpferei': 'Ton',
      'Schmuck': 'Edelstein',
      'Textil': 'Stoff',
      'Keramik': 'Ton',
      'Glas': 'Transparent',
      'Holz': 'Baum',
      'Metall': 'Schmied'
    },
    'Wissenschaft': {
      'Physik': 'Materie',
      'Chemie': 'Reaktion',
      'Biologie': 'Leben',
      'Astronomie': 'Stern',
      'Geologie': 'Erde',
      'Meteorologie': 'Wetter',
      'Ökologie': 'Natur',
      'Botanik': 'Pflanze',
      'Zoologie': 'Tier',
      'Anatomie': 'Körper',
      'Medizin': 'Heilung',
      'Psychologie': 'Geist',
      'Soziologie': 'Gesellschaft',
      'Pädagogik': 'Lernen',
      'Philosophie': 'Denken',
      'Geschichte': 'Vergangenheit',
      'Archäologie': 'Ausgrabung',
      'Linguistik': 'Sprache',
      'Mathematik': 'Zahl',
      'Statistik': 'Daten',
      'Informatik': 'Computer',
      'Robotik': 'Maschine',
      'Künstliche Intelligenz': 'Lernen',
      'Genetik': 'Erbgut',
      'Evolution': 'Entwicklung',
      'Quantenphysik': 'Atom',
      'Relativität': 'Raumzeit',
      'Kosmologie': 'Universum',
      'Nanotechnologie': 'Klein',
      'Biotechnologie': 'Leben',
      'Neurobiologie': 'Gehirn',
      'Mikrobiologie': 'Klein',
      'Virologie': 'Virus',
      'Immunologie': 'Abwehr',
      'Onkologie': 'Krebs',
      'Kardiologie': 'Herz',
      'Neurologie': 'Nerv',
      'Orthopädie': 'Knochen',
      'Dermatologie': 'Haut'
    },
    'Geschichte': {
      'Antike': 'Altertum',
      'Mittelalter': 'Ritter',
      'Renaissance': 'Kunst',
      'Aufklärung': 'Vernunft',
      'Industrialisierung': 'Fabrik',
      'Moderne': 'Neuzeit',
      'Zeitgeschichte': 'Gegenwart',
      'Prähistorie': 'Urzeit',
      'Altertum': 'Antike',
      'Frühgeschichte': 'Anfang',
      'Mittelalter': 'Ritter',
      'Neuzeit': 'Modern',
      'Gegenwart': 'Heute',
      'Zukunft': 'Morgen',
      'Revolution': 'Umsturz',
      'Krieg': 'Konflikt',
      'Frieden': 'Harmonie',
      'Demokratie': 'Volk',
      'Monarchie': 'König',
      'Diktatur': 'Herrscher',
      'Republik': 'Staat',
      'Kaiserreich': 'Kaiser',
      'Königreich': 'König',
      'Fürstentum': 'Fürst',
      'Stadtstaat': 'Stadt',
      'Bundesstaat': 'Bund',
      'Staatenbund': 'Staaten',
      'Weltreich': 'Welt',
      'Kolonialreich': 'Kolonie',
      'Imperium': 'Macht',
      'Dynastie': 'Familie',
      'Herrschaft': 'Macht',
      'Regierung': 'Staat',
      'Parlament': 'Volk',
      'Verfassung': 'Grundgesetz',
      'Gesetz': 'Recht',
      'Recht': 'Gesetz',
      'Justiz': 'Gericht',
      'Polizei': 'Ordnung'
    },
    'Geographie': {
      'Kontinent': 'Landmasse',
      'Ozean': 'Wasser',
      'Meer': 'Salz',
      'See': 'Süß',
      'Fluss': 'Wasser',
      'Berg': 'Höhe',
      'Tal': 'Senke',
      'Hügel': 'Erhebung',
      'Ebene': 'Flach',
      'Wüste': 'Sand',
      'Regenwald': 'Tropen',
      'Savanne': 'Grasland',
      'Steppe': 'Gras',
      'Tundra': 'Kalt',
      'Gletscher': 'Eis',
      'Vulkan': 'Lava',
      'Insel': 'Wasser',
      'Halbinsel': 'Land',
      'Archipel': 'Inseln',
      'Küste': 'Strand',
      'Strand': 'Sand',
      'Klippe': 'Steil',
      'Canyon': 'Schlucht',
      'Höhle': 'Dunkel',
      'Grotte': 'Höhle',
      'Fjord': 'Meer',
      'Delta': 'Mündung',
      'Mündung': 'Fluss',
      'Quelle': 'Ursprung',
      'Wasserfall': 'Fall',
      'Geysir': 'Heiß',
      'Oase': 'Wasser',
      'Atoll': 'Koralle',
      'Riff': 'Koralle',
      'Lagune': 'Meer',
      'Bucht': 'Meer',
      'Golf': 'Meer',
      'Straße': 'Meer',
      'Kanal': 'Wasser'
    },
    'Kunst': {
      'Malerei': 'Farbe',
      'Zeichnung': 'Stift',
      'Skulptur': 'Form',
      'Architektur': 'Gebäude',
      'Fotografie': 'Foto',
      'Film': 'Bewegung',
      'Musik': 'Ton',
      'Tanz': 'Bewegung',
      'Theater': 'Bühne',
      'Literatur': 'Text',
      'Poesie': 'Gedicht',
      'Design': 'Gestaltung',
      'Mode': 'Kleidung',
      'Grafik': 'Bild',
      'Illustration': 'Zeichnung',
      'Karikatur': 'Humor',
      'Comic': 'Bilder',
      'Manga': 'Japan',
      'Anime': 'Animation',
      'Kalligrafie': 'Schrift',
      'Gravur': 'Schnitt',
      'Druck': 'Presse',
      'Lithografie': 'Stein',
      'Radierung': 'Kupfer',
      'Holzschnitt': 'Holz',
      'Siebdruck': 'Schablone',
      'Töpferei': 'Ton',
      'Keramik': 'Brennen',
      'Glas': 'Transparent',
      'Schmuck': 'Edelstein',
      'Textil': 'Stoff',
      'Tapisserie': 'Wandteppich',
      'Mosaik': 'Stein',
      'Fresko': 'Wand',
      'Glasmalerei': 'Fenster',
      'Buchmalerei': 'Buch',
      'Miniatur': 'Klein',
      'Porträt': 'Gesicht',
      'Landschaft': 'Natur',
      'Stillleben': 'Objekt'
    }
  };

  // Gibt ein zufälliges Wort und seinen Hinweis aus den ausgewählten Kategorien zurück
  Map<String, String> getRandomWordWithHint(List<String> selectedCategories) {
    if (selectedCategories.isEmpty) {
      throw Exception('Keine Kategorien ausgewählt');
    }

    // Sammle alle Wörter und Hinweise aus den ausgewählten Kategorien
    List<Map<String, String>> allWordsWithHints = [];
    for (String category in selectedCategories) {
      if (categoryWords.containsKey(category)) {
        categoryWords[category]!.forEach((word, hint) {
          allWordsWithHints.add({'word': word, 'hint': hint});
        });
      }
    }

    if (allWordsWithHints.isEmpty) {
      throw Exception('Keine Wörter in den ausgewählten Kategorien gefunden');
    }

    // Wähle ein zufälliges Wort mit Hinweis aus
    allWordsWithHints.shuffle();
    return {
      'word': allWordsWithHints.first['word']!,
      'hint': allWordsWithHints.first['hint']!
    };
  }

  // Gibt alle Wörter einer bestimmten Kategorie zurück
  List<String> getWordsForCategory(String category) {
    return categoryWords[category]?.keys.toList() ?? [];
  }

  // Gibt alle verfügbaren Kategorien zurück
  List<String> getAvailableCategories() {
    return categoryWords.keys.toList();
  }
} 